{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yara-operator.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "yara-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yara-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}

